// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SignUp.proto

package grpc.ca.SignUp;

public interface HelloRequest3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name3 = 1;</code>
   */
  java.lang.String getName3();
  /**
   * <code>string name3 = 1;</code>
   */
  com.google.protobuf.ByteString
      getName3Bytes();
}
