// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SignUp.proto

package grpc.ca.SignUp;

public interface HelloReply3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloReply3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message3 = 1;</code>
   */
  java.lang.String getMessage3();
  /**
   * <code>string message3 = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessage3Bytes();
}
